# NumPy by IQRA Learnings 

## Noor Mohammed Sadiq Shaik

## What is NumPy..?

* **Linear Algebric Library** in python
* Used to perform the different **Mathematical & Logical Operations in Arrays**
* And also provides the features like **Multi Dimensional Array and Matrix** in python

In [42]:
import numpy as np

## How to create a NumPy Array..?

In numpy array there are two types of arrays i,e.
1. **1-D Array**
2. **2-D Array**

### Example of 1-D Array

In [2]:
# Example For 1-D Array
import numpy as np       # Importing NumPy as a KeyWord np
x = np.array([1,2,3])
print(x)

[1 2 3]


### Example of 2-D Array

In [6]:
# Exmple for 2-D Array
import numpy as np
y = np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


## nD-Array..?

* **Most important object defined in an NumPy** is called N-Dimensional Array and so called as **Ndarray**
* It Describes the collection of items of the same type
* Item can be accessed uding the **Zero-based Index**
* Every item in an Ndarray will takes the same space of memory
* Each Element in an Ndarray is an object of data-type object called **dtype**

# Initializing NumPy Array

## Initializing an array of 'n' X 'n' dimension with null values

In [2]:
import numpy as np
np.zeros((1,2))

array([[0., 0.]])

**Where we have to give the values as (No. of Rows   ,   No. of Colums)**

In [3]:
import numpy as np
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [4]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Arranging the numbers between x & y with an interval of z

In [15]:
import numpy as np
np.arange(10,25,5)

array([10, 15, 20])

* Where the values must be (x , y, z)
* **np.arange(Starting_Number, Ending_Number, Difference/Interval)**

In [16]:
import numpy as np
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## Arranging 'z' numbers between x & y 

In [17]:
import numpy as np
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

* Where the values are (x, y, z) in linspace
* **np.linspace(Starting_Number, Ending_Number, No.of_Points)**

In [18]:
import numpy as np
np.linspace(1,20,2)

array([ 1., 20.])

## Filling SAME number in a array of Dimension 'n' X 'n'

In [19]:
import numpy as np
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

**np.full((Rows,Columns), Filling_integer)**

In [20]:
import numpy as np
np.full((3,4),2.143)

array([[2.143, 2.143, 2.143, 2.143],
       [2.143, 2.143, 2.143, 2.143],
       [2.143, 2.143, 2.143, 2.143]])

## Filling RAMDOM number in a array of Dimension 'n' X 'n'

In [22]:
import numpy as np
np.random.random((2,2))

array([[0.66534843, 0.18194839],
       [0.69325282, 0.64721089]])

In [23]:
import numpy as np
np.random.random((2,4))

array([[0.41500242, 0.59410379, 0.18183789, 0.35412702],
       [0.26354328, 0.47319868, 0.87384375, 0.48332949]])

* **np.random.random(Rows,Columns)**
* It takes the **random() Function** and generate the random values

In [24]:
import numpy as np
np.random.random((3,4))

array([[0.8959085 , 0.15782272, 0.17681654, 0.74761457],
       [0.1320006 , 0.60038059, 0.67289529, 0.16402206],
       [0.46078491, 0.29780366, 0.21481755, 0.93745739]])

In [25]:
import numpy as np
np.random.random((10,10))

array([[0.2627212 , 0.21864415, 0.26557585, 0.38148187, 0.17186883,
        0.27061896, 0.6402099 , 0.74184699, 0.09326769, 0.6319403 ],
       [0.95873496, 0.14798439, 0.85342581, 0.73722074, 0.13920557,
        0.24666465, 0.43369433, 0.86661941, 0.53854301, 0.21545857],
       [0.48290124, 0.99847989, 0.38022058, 0.60853647, 0.82523748,
        0.56841883, 0.38266474, 0.81114857, 0.56102129, 0.90810855],
       [0.43528541, 0.2560204 , 0.43004942, 0.81514329, 0.2105269 ,
        0.47112447, 0.00685295, 0.14236587, 0.11505379, 0.71761502],
       [0.78037366, 0.88054203, 0.8548203 , 0.13052701, 0.39390592,
        0.16870308, 0.58873108, 0.7323814 , 0.36335984, 0.47321031],
       [0.36804151, 0.38101586, 0.79645447, 0.89240124, 0.72633483,
        0.52596213, 0.0465844 , 0.42190894, 0.32965018, 0.89161762],
       [0.0937231 , 0.54928045, 0.60441265, 0.94699214, 0.56618378,
        0.24938569, 0.05573101, 0.6261157 , 0.82801838, 0.25029621],
       [0.3003503 , 0.10087877, 0.4891542

# Inspestion of NumPy Array

* **Ndarray.shape()**
* **It returns a tuple consist of Array Dimension**
* Its used to **Resize** the array

In [28]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [29]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
'''print(a)'''
print(a.shape)

(4, 3)


**It returns an tuple with (Num_of_arrays, Num_of_Values_in_Array)**

In [30]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
'''print(a)'''
print(a.shape)

(8, 3)


**Resizing of an array**

In [32]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a.shape=(4,3)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


**Ndarray.size()**
* **Returns the sizr of an array**

In [34]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.size)

6


In [35]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a.size)

24


**Ndarray.dtype()**
* **Return the datatype of an array**

In [37]:
import numpy as np
c = np.arange(24,dtype=float)
print(c.size)
print(c.dtype)
v=c.reshape(3,4,2)
v

24
float64


array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]])

# NumPy Array Mathematics

## Addition Using NumPy

In [38]:
import numpy as np
np.sum([10,20,30])

60

**Adding the values in array**

In [41]:
x,y,z=10,20,30
import numpy as np
np.sum([x,y,z])

60

In [45]:
np.sum([[0,2],[0,4]], axis=0)

array([0, 6])

**Adding the axis by the value 0 & 1**

In [47]:
np.sum([[0,2],[0,4]], axis=1)

array([2, 4])

### Other Similar Mathematical Operations in NumPy are:-
* **np.subtract(x,y)**
    * **(x - y)**
* **np.divide(x,y)**
    * **(x / y)**
* **np.multiply(x,y)**
    * **(x * y)**
* **np.exp(a)**
    * **e^a**
* **np.sqrt(a)**
* **np.sin(a)**
* **np.cps(a)**
* **np.log(a)**

### Array Comparision

* There are **Two Types** of comparisions in arrays in Numpy
* **Element wise Comparrision**
* **Array wise Comparision**

**Element Wise Comparision**

In [53]:
# Element Wise Comparisoion
import numpy as np
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.equal(x,y)

array([False, False, False])

In [54]:
# Element Wise Comparisoion
import numpy as np
x = [1,2,3]
y = [4,5,6]
z = [1,2,3]
np.equal(x,z)

array([ True,  True,  True])

**Array Wise Comparision**

In [55]:
# Element Wise Comparisoion
import numpy as np
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.array_equal(x,y)

False

In [58]:
# Element Wise Comparisoion
import numpy as np
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.array_equal(x,z)

False

In [60]:
# Element Wise Comparisoion
import numpy as np
x = [1,2,3]
y = [4,5,6]
z = [1,2,3]
np.array_equal(x,z)

True

### Array Aggregate Functions

* np.sum(x)         # Array Wise Sum
* np.min(x)         # Min of Array
* np.mean(x)        # Mean of Array
* np.median(x)      # Median of Array
* np.corrcoef(x)    # Correlation coefficient of Array
* np.std(x)         # Standard Deviation of Array

In [63]:
import numpy as np
x = [1,2,4]
y = [4,5,6]
z = [7,8,9]
print(np.sum(x))         # Array Wise Sum
print(np.min(x))         # Min of Array
print(np.mean(x))        # Mean of Array
print(np.median(x))      # Median of Array
print(np.corrcoef(x))    # Correlation coefficient of Array
print(np.std(x))         # Standard Deviation of Array

7
1
2.3333333333333335
2.0
1.0
1.247219128924647


# NumPy Broadcasting

**Making the Elements set in a Set of array**

In [65]:
import numpy as np
x = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
y = np.array([0,1,2])

print('First Array',x)
print('Second Array',y)

print('First array + Second array', x + y)

First Array [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
Second Array [0 1 2]
First array + Second array [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


## Indexing & Slicing in python is as same as NumPy

**Index Refers to a Position of single_character**

* 1,2,3,4,5,6,7,8,9
* Noor Moham

* Each Character has index
* As we know that in python the index value starts from **0**

In [68]:
import numpy as np
x = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
print(x[0])
print(x[:1])

[0 0 0]
[[0 0 0]]


In [69]:
import numpy as np
x = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
print(x[0])
print(x[2])

[0 0 0]
[20 20 20]


In [70]:
import numpy as np
x = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
print(x[0])
print(x[:2,2:])

[0 0 0]
[[ 0]
 [10]]


## Array Manipulation

### Concatenation Two Arrays Together

In [71]:
import numpy as np
a = [1,2,3]
b = [4,5,6]

np.concatenate((a,b), axis = 0)

array([1, 2, 3, 4, 5, 6])

## Stack Arrays
There are **TWO** Types of stack arrays
* **Stack Array Row-Wise(Vertical)**
* **Stack Array Column-Wise(Horizantal)**

Stack Array Row-Wise(Vertical)

In [73]:
import numpy as np
a = [1,2,3]
b = [4,5,6]

np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

Stack Array Column-Wise(Horizantal)

In [74]:
import numpy as np
a = [1,2,3]
b = [4,5,6]

np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

### Combaining Column-Wise Stacked Array

In [76]:
import numpy as np
a = [1,2,3]
b = [4,5,6]

np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

### Code Explain

In [81]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,3,4],[5,6,7]])

print(np.stack((a,b),axis=0))

print('...Horizantal Stack...')
print(np.hstack((a,b)))

print('...Horizantal Concat...')
print(np.concatenate((a,b),axis=0))

print('...Vertical Stack...')
print(np.vstack((a,b)))

print('...Vertical Concat...')
print(np.concatenate((a,b),axis=1))

[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]]]
...Horizantal Stack...
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]
...Horizantal Concat...
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]
...Vertical Stack...
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]
...Vertical Concat...
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]


## Splitting an Array

In [82]:
x = np.arange(16.0).reshape(4,4)
print(x)
print(np.hsplit(x,2))
print(np.hsplit(x,np.array([3,6])))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]
[array([[ 0.,  1.,  2.],
       [ 4.,  5.,  6.],
       [ 8.,  9., 10.],
       [12., 13., 14.]]), array([[ 3.],
       [ 7.],
       [11.],
       [15.]]), array([], shape=(4, 0), dtype=float64)]


# Thats why NumPy is much better than a List

## Nimpy has completed 
## if you face any difficulties kindly reach to my e-mail
## shaiknoormohammedsadiq@gmail.com

# THANK YOU